/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletImport } from './routes/wallet'
import { Route as FriendsImport } from './routes/friends'
import { Route as EarnImport } from './routes/earn'
import { Route as BoostsImport } from './routes/boosts'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WalletRoute = WalletImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any)

const FriendsRoute = FriendsImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRoute,
} as any)

const EarnRoute = EarnImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRoute,
} as any)

const BoostsRoute = BoostsImport.update({
  id: '/boosts',
  path: '/boosts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/boosts': {
      id: '/boosts'
      path: '/boosts'
      fullPath: '/boosts'
      preLoaderRoute: typeof BoostsImport
      parentRoute: typeof rootRoute
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnImport
      parentRoute: typeof rootRoute
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boosts': typeof BoostsRoute
  '/earn': typeof EarnRoute
  '/friends': typeof FriendsRoute
  '/wallet': typeof WalletRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boosts': typeof BoostsRoute
  '/earn': typeof EarnRoute
  '/friends': typeof FriendsRoute
  '/wallet': typeof WalletRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/boosts': typeof BoostsRoute
  '/earn': typeof EarnRoute
  '/friends': typeof FriendsRoute
  '/wallet': typeof WalletRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boosts' | '/earn' | '/friends' | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boosts' | '/earn' | '/friends' | '/wallet'
  id: '__root__' | '/' | '/boosts' | '/earn' | '/friends' | '/wallet'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoostsRoute: typeof BoostsRoute
  EarnRoute: typeof EarnRoute
  FriendsRoute: typeof FriendsRoute
  WalletRoute: typeof WalletRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoostsRoute: BoostsRoute,
  EarnRoute: EarnRoute,
  FriendsRoute: FriendsRoute,
  WalletRoute: WalletRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/boosts",
        "/earn",
        "/friends",
        "/wallet"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/boosts": {
      "filePath": "boosts.tsx"
    },
    "/earn": {
      "filePath": "earn.tsx"
    },
    "/friends": {
      "filePath": "friends.tsx"
    },
    "/wallet": {
      "filePath": "wallet.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
